#!/bin/bash

while read node; do
  eval echo "Add mds1 to /etc/hosts on $node..."
  ssh -n $node "sed -i '/172.16.0.15 n015 n015.bw01.usgs.gov/a 172.16.0.22 oss1 oss1.bw01.usgs.gov' /etc/hosts"
  ssh -n $node "sed -i '/172.16.0.15 n015 n015.bw01.usgs.gov/a 172.16.0.23 oss2 oss2.bw01.usgs.gov' /etc/hosts"
  ssh -n $node "sed -i '/172.16.0.15 n015 n015.bw01.usgs.gov/a 172.16.0.24 oss3 oss3.bw01.usgs.gov' /etc/hosts"
done <n
echo done
